services:
  postgres:
    image: postgres:15.1
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - postgres_microservice_back:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: persons
      POSTGRES_PASSWORD: persons
      POSTGRES_DB:  persons
    restart: unless-stopped

  back:
    build: service_name/
    #like ais_mfr_contacts/
    command: npm run start:prod
    ports:
      - 48150:80
    depends_on:
      - postgres

  # front:
  #   build: frontend_name/.
  #   labels:
  #     SERVICE_CHECK_INTERVAL: 10s
  #   ports:
  #     - 48250:80
  #   depends_on:
  #     - back
volumes:
  postgres_microservice_back:
